import json
from typing import Any


def build_analysis_prompt(
    findings: list[dict[str, Any]],
) -> str:
    """Build an AI prompt from structured infrastructure findings."""

    findings_json = json.dumps(
        findings,
        indent=2,
        sort_keys=True,
    )

    return f"""
Analyze the following infrastructure findings.

The findings were generated by a deterministic infrastructure analyzer.
Treat them as the source of truth.

For each finding:

1. Explain the infrastructure risk in simple terms.
2. Explain why it matters.
3. Provide a practical recommendation.
4. Do not invent infrastructure resources or configuration details.
5. Do not suggest executing changes automatically.
6. Do not provide commands that modify infrastructure.

Return a concise, human-readable infrastructure analysis.

Structured findings:

{findings_json}
""".strip()
